
spring:
  datasource:
    url: jdbc:${DEVELOPMENT_DIALECT}://${DEVELOPMENT_HOST}:${DEVELOPMENT_PORT}/${DEVELOPMENT_DATABASE}
    username: ${DEVELOPMENT_USERNAME}
    password: ${DEVELOPMENT_PASSWORD}
