#Local

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/kreditunterlagen
#    username: root
#    password: 12345678
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 5
#      idle-timeout: 30000
#      max-lifetime: 600000
#      connection-timeout: 30000
#  jpa:
#    hibernate:
#      ddl-auto: none
#    open-in-view: false
#  flyway:
#    baseline-on-migrate: true
#  profiles:
#    active: dev
#  servlet:
#    multipart:
#      max-file-size: 20MB
#      max-request-size: 20MB
#  mail:
#    host: smtp.ionos.de
#    username: ub@orgaplan-beratung.de
#    password: S9ZV2T%wxhy}F+H3
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          issuer-uri: https://auth.kv.orgaplan-beratung.de/realms/kv
#          jwk-set-uri: https://auth.kv.orgaplan-beratung.de/realms/kv/protocol/openid-connect/certs

# Production

spring:
  datasource:
    url: jdbc:mysql://82.165.67.69:3306/kreditunterlagen
    username: kvapidbuser240424
    password: i75ERYnDWUMqt69VzaLB
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    baseline-on-migrate: true
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.ionos.de
    username: ub@orgaplan-beratung.de
    password: S9ZV2T%wxhy}F+H3
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://auth.kv.orgaplan-beratung.de/realms/kv
          jwk-set-uri: https://auth.kv.orgaplan-beratung.de/realms/kv/protocol/openid-connect/certs

server:
  port: 8111