spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kreditunterlagen
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: true

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
