spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kreditunterlagen
    username: root
    password: 12345678
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    baseline-on-migrate: true

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  mail:
    host: smtp.ionos.de
    username: ub@orgaplan-beratung.de
    password: S9ZV2T%wxhy}F+H3
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true