CREATE TABLE companies
(
    id                         CHAR(36)     NOT NULL PRIMARY KEY,
    user_id                    CHAR(36)     NOT NULL UNIQUE,
    is_self_employed           TINYINT(1)   NOT NULL,
    company_name               VARCHAR(255) NOT NULL,
    street_number              VARCHAR(255) NOT NULL,
    postal_code                VARCHAR(50)  NOT NULL,
    city                       VARCHAR(255) NOT NULL,
    country                    VARCHAR(255) NOT NULL,
    location                   VARCHAR(50),
    industry                   VARCHAR(255) NOT NULL,
    number_of_employees        VARCHAR(50),
    ceo                        VARCHAR(255),
    court                      VARCHAR(255),
    commercial_register_number VARCHAR(255),
    vat_id                     VARCHAR(50),
    company_email              VARCHAR(50),
    phone                      VARCHAR(50),
    fax                        VARCHAR(50),
    website                    VARCHAR(50),
    created_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);
