CREATE TABLE applicant
(
    id                        CHAR(36)                               NOT NULL PRIMARY KEY,
    selbstauskunft_id         CHAR(36)                               NOT NULL,
    first_name                VARCHAR(255)                           NOT NULL,
    last_name                 VARCHAR(255)                           NOT NULL,
    role                      ENUM ('ANTRAGSTELLER', 'LEBENPARTNER') NOT NULL,
    salutation                VARCHAR(50)                            NOT NULL,
    title                     VARCHAR(50),
    date_of_birth             DATE                                   NOT NULL,
    place_of_birth            VARCHAR(255)                           NOT NULL,
    country_of_birth          VARCHAR(255)                           NOT NULL,
    nationality               VARCHAR(255)                           NOT NULL,
    second_nationality        VARCHAR(255),
    phone                     VARCHAR(50)                            NOT NULL,
    email                     VARCHAR(255)                           NOT NULL,
    street_house_number       VARCHAR(255)                           NOT NULL,
    postal_code               VARCHAR(10)                            NOT NULL,
    city                      VARCHAR(255)                           NOT NULL,
    country                   VARCHAR(255)                           NOT NULL,
    location                  VARCHAR(50),
    residence_since           DATE,
    marital_status            VARCHAR(50)                            NOT NULL,
    tax_id                    VARCHAR(50)                            NOT NULL,
    employment_type           VARCHAR(50)                            NOT NULL,
    net_income                DECIMAL(15, 2)                         NOT NULL,
    disposable_income         DECIMAL(15, 2)                         NOT NULL,
    statutory_pension         DECIMAL(15, 2),
    private_pension           DECIMAL(15, 2),
    other_income              DECIMAL(15, 2),
    employer_name             VARCHAR(255)                           NOT NULL,
    job_title                 VARCHAR(255),
    employer_based_in_germany TINYINT(1)                             NOT NULL,
    employment_fixed_until    DATE,
    probation_until           DATE,
    retirement_date           DATE,
    credit_institute          VARCHAR(255)                           NOT NULL,
    iban                      VARCHAR(34)                            NOT NULL,
    bic                       VARCHAR(11)                            NOT NULL,
    created_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (selbstauskunft_id) REFERENCES selbstauskunft (id)
);